apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: localpool
  namespace: metallb
spec:
  #  protocol: layer2
  addresses:
    - 192.168.1.41-192.168.1.59
  autoAssign: true

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb
