apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: rook
spec:
  releaseName: rook
  chart:
    spec:
      chart: release
      sourceRef:
        kind: HelmRepository
        name: rook
        namespace: infrastructure
      version: ">=4.0.0 <5.0.0"
  targetNamespace: rook
  interval: 5m0s
  install:
    remediation:
      retries: 100
  