apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook
spec:
  releaseName: rook
  chart:
    spec:
      chart: rook-ceph
      sourceRef:
        kind: HelmRepository
        name: rook
        namespace: infrastructure
      version: "*"
  targetNamespace: rook
  interval: 5m0s
  install:
    remediation:
      retries: 100
