---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization

metadata:
  name: cluster-secret
  namespace: infrastructure
spec:
  interval: 5m0s
  path: ./yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-secret
    namespace: infrastructure-common
  targetNamespace: cluster-secret
