apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - clustersecret-source.yaml #Instead using the raw yamls untill the repo gets it fixed
  - clustersecret-kustomization.yaml
  #- 00_rbac.yaml
  #- 01_crd.yaml
  #- 02_deployment.yaml
