---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization

metadata:
  name: pgo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize/install/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-secret
    namespace: infrastructure
  targetNamespace: postgres
