# Example of PostgreSQL cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: hotlaps-prod
  namespace: hotlaps-prod
spec:
  instances: 1
  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: hotlaps-prod
      owner: hotlaps-prod-owner
  # Require 1Gi of space
  storage:
    size: 1Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "0.2"
    limits:
      memory: "256Mi"
      cpu: "0.5"
