apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: metallb
  namespace: infrastructure
spec:
  interval: 5m0s
  chart: metallb
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: metallb-crd
  version: "5.*"
