apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: infrastructure-common
spec:
  interval: 30m
  url: https://kubernetes.github.io/ingress-nginx
