apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure-common
resources:
  - namespace.yaml
  - ingress-nginx.yaml
  # - configmap-tcp-service.yaml
  - release.yaml
  # - patch-ingress-service.yaml
