apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: traefik
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      version: "*"
  targetNamespace: traefik
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
