apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: infrastructure-common
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: infrastructure-common
      #version: "*"
  targetNamespace: traefik
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
