apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: infrastructure
spec:
  releaseName: nfs-subdir-external-provisioner
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner
        namespace: infrastructure
      version: "*"
  targetNamespace: nfs-provisioner
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    storageClass:
      defaultClass: true
    nfs:
      path: /volume1/kubernetes
      server: "192.168.1.26"
