apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: infrastructure-common
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: infrastructure-common
      version: "1.x"
  targetNamespace: infrastructure-certman
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    installCRDs: true
    replicaCount: 1
