apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx
  namespace: infrastructure
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/common/nginx
  prune: true
  dependsOn:
    - name: namespaces
      namespace: flux-system
