apiVersion: v1
kind: ConfigMap
metadata:
  name: wanted-tcp-services
  namespace: ingress-nginx
data:
  tcpServices.yaml: |
    tcp:
      5432: "hotlaps-dev/hotlaps-dev-rw:5432"
      5433: "hotlaps-dev/hotlaps-dev-any:5432"
