# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: applications
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   path: ./applications
#   prune: true
#   dependsOn:
#     - name: infrastructure-common
