apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: database-prod
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./database/prod
  prune: true
  dependsOn:
    - name: namespaces
      namespace: flux-system
    - name: infrastructure-common
      namespace: flux-system
