apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-ca
  namespace: certman
spec:
  isCA: true
  duration: 26000h # 3Y
  secretName: localk8sdev-ca-secret
  commonName: localk8sdev-ca
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
