apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: localhost-tls
  namespace: default
spec:
  secretName: localhost-tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - localhost
