apiVersion: v1
kind: ConfigMap
metadata:
  name: wanted-tcp-services
  namespace: ingress-nginx
data:
  tcpServices.yaml: |
    tcp:
      5432: "hotlaps-prod/hotlaps-prod-rw:5432"
      5433: "hotlaps-test/hotlaps-test-rw:5432"
