apiVersion: v1
kind: ConfigMap
metadata:
  name: wanted-tcp-services
  namespace: infrastructure
data:
  tcpServices.yaml: |
    tcp:
      5432: "hotlaps-prod/hotlaps-prod-rw:5432"
      5433: "hotlaps-prod/hotlaps-prod-any:5432"
