apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: localpool
  namespace: infrastructure-metallb
spec:
  #  protocol: layer2
  addresses:
    - 192.168.1.41-192.168.1.59
  autoAssign: false
