apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hotlaps-dev
resources:
  - namespace-metallb.yaml
  - repository-metallb.yaml
  - release-metallb.yaml
  - config-metallb.yaml
