apiVersion: v1
kind: ConfigMap
metadata:
  name: wanted-tcp-services
  namespace: infrastructure
data:
  tcpServices.yaml: |
    tcp:
      5432: "default/example-tcp-svcA:5432"
      5433: "default/example-tcp-svcB:5432"
