apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: infrastructure
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: infrastructure
      version: ">=4.0.0 <5.0.0"
  targetNamespace: ingress-nginx
  interval: 5m0s
  install:
    remediation:
      retries: 100
  values: #Decides whether its a loadbalanced service or just a nodeport mapping
    controller:
      hostPort:
        enabled: true
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
