apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: emberstack
  namespace: infrastructure-common
spec:
  interval: 30m
  url: https://emberstack.github.io/helm-charts
