apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: infrastructure-common
spec:
  releaseName: reflector
  chart:
    spec:
      chart: reflector
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: infrastructure-common
  targetNamespace: infrastructure-reflector
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
