---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization

metadata:
  name: pgo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize/install/namespace
  prune: true
  sourceRef:
    kind: GitRepository
    name: pgo
  targetNamespace: postgres
  # patchesStrategicMerge:
  #   - |-
  #     apiVersion: apps/v1
  #     kind: Deployment
  #     metadata:
  #       name: pgo
  #     spec:
  #       template:
  #         spec:
  #           containers:
  #           - name: operator
  #             env:
  #             - name: CRUNCHY_DEBUG
  #               value: "false"
