apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-kind
  namespace: infrastructure
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: infrastructure
      version: ">=4.0.0 <5.0.0"
  targetNamespace: ingress-nginx
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    controller:
      hostPort:
        enabled: true
      service:
        type: NodePort
