apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: infrastructure-common
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: infrastructure-common
      version: ">=4.0.0 <5.0.0"
  targetNamespace: ingress-nginx
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    # tcp:
    #  5432: "hotlaps-dev/hotlaps-dev-rw:5432"
    #   installCRDs: true
    #   replicaCount: 1
    service:
      type: nodeport
    controller:
      extraArgs:
        tcp-services-configmap: "ingress-nginx/tcp-services"
